### ISSUE TITLE
pip can't find blockscore 4.0.0 on pypi

### ISSUE THREAD

**Issue by zenryan** [BlockScore/blockscore-python#11]
pip is unable to install version 4.0.0 from pypi

It looks like there isn't a file released for 4.0.0. Compare https://pypi.python.org/pypi/blockscore/4.0.0 to https://pypi.python.org/pypi/blockscore/3.0.0

**Comment by backus** [comment]
Sorry about that. I'm looking into pushing a fix now.

**Comment by backus** [comment]
It should be up now @zenryan https://pypi.python.org/pypi/blockscore/4.0.0. Thanks for pointing that out.

**Comment by zenryan** [comment]
thank you!
