### ISSUE TITLE
Receiving non-json based responses

### ISSUE THREAD

**Issue by zenryan** [BlockScore/blockscore-python#12]
Hey @alainmeier, I've been running this lib in production for a couple days now and it seems like every once in awhile a response will come back with non-json content type. In what cases will this occur? As a result, a python error gets thrown while checking for error at line 18 in error_handler.py because the response body is not a dictionary.

**Comment by alainmeier** [comment]
Hi Ryan, this is happening because sometimes the IRS takes a very long time to respond to us. We're putting better handling in place for this, sorry about the inconvenience!

**Comment by zenryan** [comment]
What's the content body look like for one of these responses? Also, would you suggest re-running the failed verifications at a later time?

**Comment by alainmeier** [comment]
The bad responses will be HTML from Heroku saying that a request timed out. 

And yes, I would recommend waiting and then trying again. Sometimes the IRS outages are for a couple seconds, sometimes they're for a couple of hours, unfortunately. We made the decision to make it synchronous a ways back to make implementation easier for customers but will likely be implementing a callback-style method in v5 of the API to handle for cases like this.

**Comment by zenryan** [comment]
Makes sense, thanks for the response. I'll take that into account and re-run any that fail.
